# Generated by Django 3.1.1 on 2020-09-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoastsRoastsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isboast', models.BooleanField()),
                ('post_body', models.CharField(max_length=280)),
                ('post_upvote', models.IntegerField(default=0)),
                ('post_downvote', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('s_key', models.CharField(max_length=10)),
            ],
        ),
    ]
